### ISSUE TITLE
更改库存获取语言

### ISSUE THREAD

**Issue by SparkUiX** [itzdrli/koishi-plugin-cs-lookup#1]
官方API
https://steamcommunity.com/inventory/ {steamid} /730/2?l=schinese&count=1000
有墙
其中参数
l是语言，schinese是简体中文
count 最大获取数量
只要Steamid就可以
建议加上获取库存失败告诉用户去打开库存公开权限
（

**Comment by itzdrli** [comment]
# cs-lookup v0.2.1
